---

- name: Clean up on ECP
  hosts: localhost
  connection: local
  remote_user: opensuse
  tasks:

    - name: Load constants
      include_vars:
        file: constants.yml
      tags:
        - always

    - name: Load variables
      include_vars:
        file: variables.yml
      tags:
        - always

    - name: Delete OpenStack based server
      include_role:
        name: cleanup_openstack
      when: provision_type == "openstack"
