---

- name: Load variables
  include_vars:
    file: variables.yml
  tags:
    - always

- name: Clone openstack-ansible repository
  become: yes
  git:
    clone: yes
    dest: "{{ osa_repodir }}"
    repo: "{{ osa_repository }}"
    update: yes
    force: yes
    version: "{{ osa_tag }}"
  tags:
    - setup_osa

- name: Reset and clean openstack-ansible repository so we can apply the patches
  become: yes
  shell: git reset --hard && git clean -dfx
  args:
    chdir: "{{ osa_repodir }}"
  tags:
    - setup_osa

- name: Bootstrap ansible
  become: yes
  command: ./scripts/bootstrap-ansible.sh
  args:
    chdir: "{{ osa_repodir }}"
  register: bootstrap_ansible
  until: bootstrap_ansible is succeeded
  retries: 1
  async: 1200
  poll: 10
  tags:
    - setup_osa
    - bootstrap_ansible

- name: Bootstrap AIO
  become: yes
  shell: ./scripts/bootstrap-aio.sh
  args:
    chdir: "{{ osa_repodir }}"
    executable: /bin/bash
  environment:
    PATH: "/usr/local/bin:{{ lookup('env', 'PATH') }}"
    SCENARIO: "octavia"
  register: bootstrap_aio
  until: bootstrap_aio is succeeded
  retries: 1
  async: 1200
  poll: 10
  tags:
    - setup_osa
    - bootstrap_aio
