---

- name: Load constants
  include_vars:
    file: constants.yml
  tags:
    - always

- name: Load variables
  include_vars:
    file: variables.yml
  tags:
    - always

- name: "Clone openstack-ansible repository (at tag {{ osa_tag }})"
  become: yes
  git:
    clone: yes
    dest: "{{ osa_repodir }}"
    repo: "{{ osa_repository }}"
    update: yes
    force: yes
    version: "{{ osa_tag }}"
  tags:
    - clone_osa_repo

- name: Run upstream test job
  include_tasks: upstream.yml
  when: osa_job == "upstream"
  tags:
    - setup_osa

- name: Run workshop job
  include_tasks: workshop.yml
  when: osa_job == "workshop"
  tags:
    - setup_osa
