---

- name: Run gate job
  shell: |
    tmux new-session -d -s upstream-gate
    tmux send-keys "sudo su -" Enter
    tmux send-keys "cd {{ osa_repodir }}" Enter
    tmux send-keys "./scripts/gate-check-commit.sh \
      {{ osa_scenario }} {{ osa_action }} {{ osa_install_method }}" Enter
  tags:
    - setup_osa
